# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.PDSm
canonical: http://interop.esante.gouv.fr/ci-sis/fhir/PDSm
name: PDSm
title: Partage de Documents de Santé en mobilité (PDSm)
publisher:
    name: ANS
    url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build

dependencies:
    ihe.iti.mhd: 4.1.0
    ans.annuaire.fhir.r4: 0.2.0
    # TODO: rajouter fr-core # 
    hl7.fhir.fr.core: 1.1.0

parameters:
    shownav: 'true'

pages:
    index.md:
        title: Accueil
    specifications_techniques.md:
        construction_des_flux.md:
        st_ajout.md:
            title: Ajout d'un lot de documents
        st_maj.md:
            title: Mise à jour de documents
        st_recherche_lot.md:
            title: Recherche de lot de soumission
        st_recherche_fiche.md:
            title: Recherche de fiche
        st_consultation.md:
            title: Consultation de documents
        st_ajout_simplifie.md:
            title: Ajout simplifié d'un document
    # specifications_fonctionnelles.md:
    #     sf_ajout.md:
    #         title: Ajout d'un lot de documents
    #     sf_maj.md:
    #         title: Mise à jour de documents
    #     sf_recherche.md:
    #         title: Recherche de documents
    #     sf_consultation.md:
    #         title: Consultation de documents
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        equivalences.md:
            title: Equivalences
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Description des flux:
        Vue d'ensemble: construction_des_flux.html
        Ajout d'un lot de documents: st_ajout.html 
        Mise à jour de documents: st_maj.html
        Recherche de lot de documents: st_recherche_lot.html
        Recherche de fiche: st_recherche_fiche.html
        Consultation de documents: st_consultation.html
        Ajout simplifié d'un document: st_ajout_simplifie.html
    # Spécifications fonctionnelles:
    #     Spécifications fonctionnelles: specifications_fonctionnelles.html
    #     Ajout d'un lot de documents: sf_ajout.html
    #     Mise à jour de documents: sf_maj.html
    #     Recherche de documents: sf_recherche.html
    #     Consultation de documents: sf_consultation.html
    Ressources de conformance: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        Equivalences: equivalences.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
